<?php
	/*
	 * PzPHP Core Directory Constants
	 */
	define('PZPHP_INC_DIR', BASE_DIR.'Pzphp'.DIRECTORY_SEPARATOR);
	define('PZPHP_RESOURCES_DIR', BASE_DIR.'Resources'.DIRECTORY_SEPARATOR);
	define('PZPHP_TRANSLATIONS_DIR', PZPHP_RESOURCES_DIR.'translations'.DIRECTORY_SEPARATOR);
	define('PZPHP_CSS_DIR', PZPHP_RESOURCES_DIR.'css'.DIRECTORY_SEPARATOR);
	define('PZPHP_JS_DIR', PZPHP_RESOURCES_DIR.'js'.DIRECTORY_SEPARATOR);
	define('PZPHP_IMAGES_DIR', PZPHP_RESOURCES_DIR.'images'.DIRECTORY_SEPARATOR);

	/*
	 * Caching Methods
	 */
	define('PZPHP_CACHE_MODE_NO_CACHING', 0);
	define('PZPHP_CACHE_MODE_SHARED_MEMORY', 1);
	define('PZPHP_CACHE_MODE_APC', 2);
	define('PZPHP_CACHE_MODE_MEMCACHE', 3);
	define('PZPHP_CACHE_MODE_MEMCACHED', 4);
	define('PZPHP_CACHE_MODE_LOCALCACHE', 5);

	/*
	 * Database systems
	 */
	define('PZPHP_DATABASE_MYSQLI', 0);
	define('PZPHP_DATABASE_MYSQL', 1);
	define('PZPHP_DATABASE_PDO_CUBRID', 'cubrid');
	define('PZPHP_DATABASE_PDO_MSSQL', 'mssql');
	define('PZPHP_DATABASE_PDO_SYBASE', 'sybase');
	define('PZPHP_DATABASE_PDO_DBLIB', 'dblib');
	define('PZPHP_DATABASE_PDO_FIREBIRD', 'firebird');
	define('PZPHP_DATABASE_PDO_IBM', 'ibm');
	define('PZPHP_DATABASE_PDO_INFORMIX', 'informix');
	define('PZPHP_DATABASE_PDO_MYSQL', 'mysql');
	define('PZPHP_DATABASE_PDO_SQLSRV', 'sqlsrv');
	define('PZPHP_DATABASE_PDO_ORACLE', 'oci');
	define('PZPHP_DATABASE_PDO_ODBC', 'odbc');
	define('PZPHP_DATABASE_PDO_ODBC_IBMDB2', 'odbcibmdb2');
	define('PZPHP_DATABASE_PDO_ODBC_MSACCSS', 'odbcmsaccss');
	define('PZPHP_DATABASE_PDO_POSTGRESQL', 'pgsql');
	define('PZPHP_DATABASE_PDO_SQLITE', 'sqlite');
	define('PZPHP_DATABASE_PDO_SQLITE2', 'sqlite2');
	define('PZPHP_DATABASE_PDO_4D', '4d');

	/*
	 * PzPHP settings
	 */
	define('PZPHP_CACHING_MODE', PZPHP_CACHE_MODE_NO_CACHING);
	define('PZPHP_DATABASE_MODE', PZPHP_DATABASE_MYSQLI);

	/*
	 * Pz_Security Settings
	 */
	define('PZ_SECURITY_HASH_TABLE', '');
	define('PZ_SECURITY_SALT', '');
	define('PZ_SECURITY_POISON_CONSTRAINTS', '');
	define('PZ_SECURITY_REHASH_DEPTH', '');

	/*
	 * Pz specific settings
	 */
	define('PZ_SETTING_DB_CONNECT_RETRY_ATTEMPTS', 1);
	define('PZ_SETTING_DB_CONNECT_RETRY_DELAY', 2);
	define('PZ_SETTING_DB_AUTO_CONNECT_SERVER', false);
	define('PZ_SETTING_DB_AUTO_ASSIGN_ACTIVE_SERVER', true);
	define('PZ_SETTING_DB_WRITE_RETRY_FIRST_INTERVAL_DELAY', 3000000);
	define('PZ_SETTING_DB_WRITE_RETRY_SECOND_INTERVAL_DELAY', 500000);
	define('PZ_SETTING_DB_WRITE_RETRY_FIRST_INTERVAL_RETRIES', 3);
	define('PZ_SETTING_DB_WRITE_RETRY_SECOND_INTERVAL_RETRIES', 6);

	define('PZ_SETTING_CACHE_CONNECT_RETRY_ATTEMPTS', 1);
	define('PZ_SETTING_CACHE_CONNECT_RETRY_DELAY', 2);
	define('PZ_SETTING_CACHE_AUTO_CONNECT_SERVER', false);
	define('PZ_SETTING_CACHE_AUTO_ASSIGN_ACTIVE_SERVER', true);

	define('PZ_SETTING_OUTPUT_COMPRESSION', true);
	define('PZ_SETTING_OUTPUT_BUFFERING', true);

	define('PZ_SETTING_DOMAIN_PROTECTION', false);
	define('PZ_SETTING_DOMAIN_ALLOWED_DOMAINS', '');
	define('PZ_SETTING_DOMAIN_TARGET_DOMAIN', '');

	define('PZ_SETTING_DEBUG_MODE', true);
	define('PZ_SETTING_DEBUG_ERROR_LOGGING', true);
	define('PZ_SETTING_DEBUG_DISPLAY_BAR', false);
	define('PZ_SETTING_DEBUG_DB_USER', '');
	define('PZ_SETTING_DEBUG_DB_PASSWORD', '');
	define('PZ_SETTING_DEBUG_DB_NAME', '');
	define('PZ_SETTING_DEBUG_DB_HOST', 'localhost');
	define('PZ_SETTING_DEBUG_DB_PORT', 3306);
	define('PZ_SETTING_DEBUG_DB_LOG', false);
	define('PZ_SETTING_DEBUG_LOG_FILE_AUTO_ROTATE', true);
	define('PZ_SETTING_DEBUG_DELETE_LOG_FILES_AFTER_X_DAYS', 7);
	define('PZ_SETTING_DEBUG_MYSQL_LOG_ERRORS', true);
	define('PZ_SETTING_DEBUG_MYSQL_ERROR_LOG_FILE_NAME', 'MYSQL_ERRORS');
	define('PZ_SETTING_DEBUG_MEMCACHE_LOG_ERRORS', true);
	define('PZ_SETTING_DEBUG_MEMCACHE_ERROR_LOG_FILE_NAME', 'MEMCACHE_ERRORS');
	define('PZ_SETTING_DEBUG_MEMCACHED_LOG_ERRORS', true);
	define('PZ_SETTING_DEBUG_MEMCACHED_ERROR_LOG_FILE_NAME', 'MEMCACHED_ERRORS');
	define('PZ_SETTING_DEBUG_PDO_LOG_ERRORS', true);
	define('PZ_SETTING_DEBUG_PDO_ERROR_LOG_FILE_NAME', 'PDO_ERRORS');
	define('PZ_SETTING_DEBUG_LOG_PHP_ERRORS', true);
	define('PZ_SETTING_DEBUG_PHP_ERROR_LOG_FILE_NAME', 'PHP_ERRORS');
	define('PZ_SETTING_DEBUG_PHP_DISPLAY_ERRORS', false);

	define('PZ_SETTING_WHITELIST_IP_CHECK', false);
	define('PZ_SETTING_WHITELIST_IPS', '');
	define('PZ_SETTING_WHITELIST_ACTION', 'a:3:{s:6:"action";s:4:"exit";s:6:"target";s:0:"";s:7:"message";s:22:"<h1>Access Denied</h1>";}');
	define('PZ_SETTING_WHITELIST_AUTO_ALLOW_HOST_SERVER_IP', true);

	define('PZ_SETTING_BLACKLIST_IP_CHECK', false);
	define('PZ_SETTING_BLACKLIST_IPS', '');
	define('PZ_SETTING_BLACKLIST_ACTION', 'a:3:{s:6:"action";s:4:"exit";s:6:"target";s:0:"";s:7:"message";s:47:"<h1>You have been banned from this website</h1>";}');
	define('PZ_SETTING_BLACKLIST_IGNORE_HOST_SERVER_IP', true);
