<?php
	/*
	 * PzPHP Core Directory Constants
	 */
	$PZ_CONFIG_ARRAY['PZPHP_INC_DIR'] = $PZ_CONFIG_ARRAY['BASE_DIR'].'Pzphp'.DIRECTORY_SEPARATOR;
	$PZ_CONFIG_ARRAY['PZPHP_RESOURCES_DIR'] = $PZ_CONFIG_ARRAY['BASE_DIR'].'Resources'.DIRECTORY_SEPARATOR;
	$PZ_CONFIG_ARRAY['PZPHP_VIEWS_DIR'] = $PZ_CONFIG_ARRAY['PZPHP_RESOURCES_DIR'].'views'.DIRECTORY_SEPARATOR;
	$PZ_CONFIG_ARRAY['PZPHP_TRANSLATIONS_DIR'] = $PZ_CONFIG_ARRAY['PZPHP_RESOURCES_DIR'].'translations'.DIRECTORY_SEPARATOR;
	$PZ_CONFIG_ARRAY['PZPHP_CSS_DIR'] = $PZ_CONFIG_ARRAY['PZPHP_RESOURCES_DIR'].'css'.DIRECTORY_SEPARATOR;
	$PZ_CONFIG_ARRAY['PZPHP_JS_DIR'] = $PZ_CONFIG_ARRAY['PZPHP_RESOURCES_DIR'].'js'.DIRECTORY_SEPARATOR;
	$PZ_CONFIG_ARRAY['PZPHP_IMAGES_DIR'] = $PZ_CONFIG_ARRAY['PZPHP_RESOURCES_DIR'].'images'.DIRECTORY_SEPARATOR;

	/*
	 * Caching Methods
	 */
	$PZ_CONFIG_ARRAY['PZPHP_CACHE_MODE_NO_CACHING'] = 0;
	$PZ_CONFIG_ARRAY['PZPHP_CACHE_MODE_SHARED_MEMORY'] = 1;
	$PZ_CONFIG_ARRAY['PZPHP_CACHE_MODE_APC'] = 2;
	$PZ_CONFIG_ARRAY['PZPHP_CACHE_MODE_MEMCACHE'] = 3;
	$PZ_CONFIG_ARRAY['PZPHP_CACHE_MODE_MEMCACHED'] = 4;
	$PZ_CONFIG_ARRAY['PZPHP_CACHE_MODE_LOCALCACHE'] = 5;

	/*
	 * Database systems
	 */
	$PZ_CONFIG_ARRAY['PZPHP_DATABASE_MYSQLI'] = 0;
	$PZ_CONFIG_ARRAY['PZPHP_DATABASE_MYSQL'] = 1;
	$PZ_CONFIG_ARRAY['PZPHP_DATABASE_PDO_CUBRID'] = 'cubrid';
	$PZ_CONFIG_ARRAY['PZPHP_DATABASE_PDO_MSSQL'] = 'mssql';
	$PZ_CONFIG_ARRAY['PZPHP_DATABASE_PDO_SYBASE'] = 'sybase';
	$PZ_CONFIG_ARRAY['PZPHP_DATABASE_PDO_DBLIB'] = 'dblib';
	$PZ_CONFIG_ARRAY['PZPHP_DATABASE_PDO_FIREBIRD'] = 'firebird';
	$PZ_CONFIG_ARRAY['PZPHP_DATABASE_PDO_IBM'] = 'ibm';
	$PZ_CONFIG_ARRAY['PZPHP_DATABASE_PDO_INFORMIX'] = 'informix';
	$PZ_CONFIG_ARRAY['PZPHP_DATABASE_PDO_MYSQL'] = 'mysql';
	$PZ_CONFIG_ARRAY['PZPHP_DATABASE_PDO_SQLSRV'] = 'sqlsrv';
	$PZ_CONFIG_ARRAY['PZPHP_DATABASE_PDO_ORACLE'] = 'oci';
	$PZ_CONFIG_ARRAY['PZPHP_DATABASE_PDO_ODBC'] = 'odbc';
	$PZ_CONFIG_ARRAY['PZPHP_DATABASE_PDO_ODBC_IBMDB2'] = 'odbcibmdb2';
	$PZ_CONFIG_ARRAY['PZPHP_DATABASE_PDO_ODBC_MSACCSS'] = 'odbcmsaccss';
	$PZ_CONFIG_ARRAY['PZPHP_DATABASE_PDO_POSTGRESQL'] = 'pgsql';
	$PZ_CONFIG_ARRAY['PZPHP_DATABASE_PDO_SQLITE'] = 'sqlite';
	$PZ_CONFIG_ARRAY['PZPHP_DATABASE_PDO_SQLITE2'] = 'sqlite2';
	$PZ_CONFIG_ARRAY['PZPHP_DATABASE_PDO_4D'] = '4d';

	/*
	 * PzPHP settings
	 */
	$PZ_CONFIG_ARRAY['PZPHP_CACHING_MODE'] = $PZ_CONFIG_ARRAY['PZPHP_CACHE_MODE_NO_CACHING'];
	$PZ_CONFIG_ARRAY['PZPHP_DATABASE_MODE'] = $PZ_CONFIG_ARRAY['PZPHP_DATABASE_MYSQLI'];

	/*
	 * Pz_Security Settings
	 */
	$PZ_CONFIG_ARRAY['PZ_SECURITY_HASH_TABLE'] = array();
	$PZ_CONFIG_ARRAY['PZ_SECURITY_SALT'] = '';
	$PZ_CONFIG_ARRAY['PZ_SECURITY_POISON_CONSTRAINTS'] = array();
	$PZ_CONFIG_ARRAY['PZ_SECURITY_REHASH_DEPTH'] = '';

	/*
	 * Pz specific settings
	 */
	$PZ_CONFIG_ARRAY['PZ_SETTING_DB_CONNECT_RETRY_ATTEMPTS'] = 1;
	$PZ_CONFIG_ARRAY['PZ_SETTING_DB_CONNECT_RETRY_DELAY'] = 2;
	$PZ_CONFIG_ARRAY['PZ_SETTING_DB_AUTO_CONNECT_SERVER'] = false;
	$PZ_CONFIG_ARRAY['PZ_SETTING_DB_AUTO_ASSIGN_ACTIVE_SERVER'] = true;
	$PZ_CONFIG_ARRAY['PZ_SETTING_DB_WRITE_RETRY_FIRST_INTERVAL_DELAY'] = 3000000;
	$PZ_CONFIG_ARRAY['PZ_SETTING_DB_WRITE_RETRY_SECOND_INTERVAL_DELAY'] = 500000;
	$PZ_CONFIG_ARRAY['PZ_SETTING_DB_WRITE_RETRY_FIRST_INTERVAL_RETRIES'] = 3;
	$PZ_CONFIG_ARRAY['PZ_SETTING_DB_WRITE_RETRY_SECOND_INTERVAL_RETRIES'] = 6;

	$PZ_CONFIG_ARRAY['PZ_SETTING_CACHE_CONNECT_RETRY_ATTEMPTS'] = 1;
	$PZ_CONFIG_ARRAY['PZ_SETTING_CACHE_CONNECT_RETRY_DELAY'] = 2;
	$PZ_CONFIG_ARRAY['PZ_SETTING_CACHE_AUTO_CONNECT_SERVER'] = false;
	$PZ_CONFIG_ARRAY['PZ_SETTING_CACHE_AUTO_ASSIGN_ACTIVE_SERVER'] = true;
	$PZ_CONFIG_ARRAY['PZ_SETTING_CACHE_LOCK_EXPIRE_TIME'] = 15;

	$PZ_CONFIG_ARRAY['PZ_SETTING_OUTPUT_COMPRESSION'] = true;
	$PZ_CONFIG_ARRAY['PZ_SETTING_OUTPUT_BUFFERING'] = true;

	$PZ_CONFIG_ARRAY['PZ_SETTING_DOMAIN_PROTECTION'] = false;
	$PZ_CONFIG_ARRAY['PZ_SETTING_DOMAIN_ALLOWED_DOMAINS'] = '';
	$PZ_CONFIG_ARRAY['PZ_SETTING_DOMAIN_TARGET_DOMAIN'] = '';

	$PZ_CONFIG_ARRAY['PZ_SETTING_DEBUG_MODE'] = true;
	$PZ_CONFIG_ARRAY['PZ_SETTING_DEBUG_ERROR_LOGGING'] = true;
	$PZ_CONFIG_ARRAY['PZ_SETTING_DEBUG_DISPLAY_BAR'] = false;
	$PZ_CONFIG_ARRAY['PZ_SETTING_DEBUG_DB_USER'] = '';
	$PZ_CONFIG_ARRAY['PZ_SETTING_DEBUG_DB_PASSWORD'] = '';
	$PZ_CONFIG_ARRAY['PZ_SETTING_DEBUG_DB_NAME'] = '';
	$PZ_CONFIG_ARRAY['PZ_SETTING_DEBUG_DB_HOST'] = 'localhost';
	$PZ_CONFIG_ARRAY['PZ_SETTING_DEBUG_DB_PORT'] = 3306;
	$PZ_CONFIG_ARRAY['PZ_SETTING_DEBUG_DB_LOG'] = false;
	$PZ_CONFIG_ARRAY['PZ_SETTING_DEBUG_LOG_FILE_AUTO_ROTATE'] = true;
	$PZ_CONFIG_ARRAY['PZ_SETTING_DEBUG_DELETE_LOG_FILES_AFTER_X_DAYS'] = 7;
	$PZ_CONFIG_ARRAY['PZ_SETTING_DEBUG_MYSQL_LOG_ERRORS'] = true;
	$PZ_CONFIG_ARRAY['PZ_SETTING_DEBUG_MYSQL_ERROR_LOG_FILE_NAME'] = 'MYSQL_ERRORS';
	$PZ_CONFIG_ARRAY['PZ_SETTING_DEBUG_MEMCACHE_LOG_ERRORS'] = true;
	$PZ_CONFIG_ARRAY['PZ_SETTING_DEBUG_MEMCACHE_ERROR_LOG_FILE_NAME'] = 'MEMCACHE_ERRORS';
	$PZ_CONFIG_ARRAY['PZ_SETTING_DEBUG_MEMCACHED_LOG_ERRORS'] = true;
	$PZ_CONFIG_ARRAY['PZ_SETTING_DEBUG_MEMCACHED_ERROR_LOG_FILE_NAME'] = 'MEMCACHED_ERRORS';
	$PZ_CONFIG_ARRAY['PZ_SETTING_DEBUG_PDO_LOG_ERRORS'] = true;
	$PZ_CONFIG_ARRAY['PZ_SETTING_DEBUG_PDO_ERROR_LOG_FILE_NAME'] = 'PDO_ERRORS';
	$PZ_CONFIG_ARRAY['PZ_SETTING_DEBUG_LOG_PHP_ERRORS'] = true;
	$PZ_CONFIG_ARRAY['PZ_SETTING_DEBUG_PHP_ERROR_LOG_FILE_NAME'] = 'PHP_ERRORS';
	$PZ_CONFIG_ARRAY['PZ_SETTING_DEBUG_PHP_DISPLAY_ERRORS'] = false;
